// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CMS.Data.DataEntity
{
    public partial class ArticleType
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}