// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CMS.Data.DataEntity
{
    public partial class Article
    {
        public int Id { get; set; }
        public int? ArticleTypeId { get; set; }
        public string ArticleCategoryIds { get; set; }
        public int? ProductBrandId { get; set; }
        public int? ArticleStatusId { get; set; }
        public string Name { get; set; }
        public string SubTitle { get; set; }
        public string Image { get; set; }
        public string ImageDescription { get; set; }
        public string BannerImage { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string Author { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool? Active { get; set; }
        public int? Counter { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public string CheckBy { get; set; }
        public DateTime? CheckDate { get; set; }
        public string ApproveBy { get; set; }
        public DateTime? ApproveDate { get; set; }
        public string Url { get; set; }
        public string Tags { get; set; }
        public bool? CanCopy { get; set; }
        public bool? CanComment { get; set; }
        public bool? CanDelete { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }
    }
}