// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CMS.Data.DataEntity
{
    public partial class ArticleComment
    {
        public int Id { get; set; }
        public int? ArticleId { get; set; }
        public int? ParentCommentId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Content { get; set; }
        public bool? Active { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateBy { get; set; }
    }
}