// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CMS.Data.DataEntity
{
    public partial class ArticleCategoryArticle
    {
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public int ArticleCategoryId { get; set; }
    }
}