// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CMS.Data.DataEntity
{
    public partial class ArticleBlock
    {
        public int Id { get; set; }
        public int? ArticleCategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public bool? Active { get; set; }
        public int? Sort { get; set; }
        public int? StyleId { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string LastEditedBy { get; set; }
        public DateTime? LastEditedDate { get; set; }
        public bool? CanDelete { get; set; }
    }
}