// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CMS.Data.DataEntity
{
    public partial class AspNetUserProfiles
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string RegType { get; set; }
        public DateTime? RegisterDate { get; set; }
        public bool? Verified { get; set; }
        public DateTime? VerifiedDate { get; set; }
        public DateTime? LastActivityDate { get; set; }
        public string FullName { get; set; }
        public bool? Gender { get; set; }
        public DateTime? BirthDate { get; set; }
        public string Company { get; set; }
        public int? ProductBrandId { get; set; }
        public int? Rank { get; set; }
        public string Address { get; set; }
        public int? CountryId { get; set; }
        public int? LocationId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string FacebookId { get; set; }
        public string Skype { get; set; }
        public string AvatarUrl { get; set; }
        public string Signature { get; set; }
        public int? AccountType { get; set; }
        public string Department { get; set; }
    }
}