// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CMS.Data.DataEntity
{
    public partial class Setting
    {
        public int Id { get; set; }
        public string Domain { get; set; }
        public string WebsiteName { get; set; }
        public string AdminName { get; set; }
        public string EmailSupport { get; set; }
        public string EmailOrder { get; set; }
        public string EmailSenderSmtp { get; set; }
        public string EmailSenderPort { get; set; }
        public bool? EmailSenderSsl { get; set; }
        public string EmailSender { get; set; }
        public string EmailSenderPassword { get; set; }
        public string Telephone { get; set; }
        public bool AppStatus { get; set; }
        public int? Counter { get; set; }
        public int DefaultLanguageId { get; set; }
        public int DefaultSkinId { get; set; }
        public string MetaDescriptionDefault { get; set; }
        public string MetaKeywordsDefault { get; set; }
        public string MetaTitleDefault { get; set; }
        public string GoogleAnalyticsCode { get; set; }
        public string OtherCode { get; set; }
        public string FacebookPageId { get; set; }
        public string FacebookAppId { get; set; }
        public string FacebookAdmin { get; set; }
        public string TwitterId { get; set; }
        public string VbeeAppId { get; set; }
        public string VbeeUserId { get; set; }
    }
}